### ISSUE TITLE
local-gpu docker-compose version incompatibility

### ISSUE THREAD

**Issue by shakedel** [aws-samples/amazon-sagemaker-local-mode#36]
When I try to `estimator.fit()` with a `local_gpu` instance type, I get the following error:
> The Compose file '/tmp/tmpemtqjw1x/docker-compose.yaml' is invalid because:
> Unsupported config option for services.algo-1-x260e: 'deploy'

The generated YAML is:
```
networks:
  sagemaker-local:
    name: sagemaker-local
services:
  algo-1-lrlsg:
    command: train
    container_name: anj25ec7e5-algo-1-lrlsg
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
    environment:
    - AWS_REGION=eu-central-1
    - TRAINING_JOB_NAME=my_ecr-2023-07-03-21-51-01-644
    image: xxxxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/my_ecr:latest
    networks:
      sagemaker-local:
        aliases:
        - algo-1-lrlsg
    stdin_open: true
    tty: true
    volumes:
    - /tmp/tmp56de_vqt/algo-1-lrlsg/output:/opt/ml/output
    - /tmp/tmp56de_vqt/algo-1-lrlsg/output/data:/opt/ml/output/data
    - /tmp/tmp56de_vqt/algo-1-lrlsg/input:/opt/ml/input
    - /tmp/tmp56de_vqt/model:/opt/ml/model
    - /home/ubuntu/work/feuerkrieg_division:/opt/ml/input/data/instance
version: '2.3'
```

I am new to docker compose, but after reading a bit I think the problem is that `deploy` was introduced in v3, but that the YAML version is 2.3
Also I dont know how this interacts with the fact that I had to install v1 (`docker-compose` rather than `docker compose`) for the execution to reach this failure.
I saw no ENV_VAR I could set to change either:
* The `docker-compose` command https://github.com/aws/sagemaker-python-sdk/blob/052d7e00f236b19260b584ee7d63e2141e5053fb/src/sagemaker/local/image.py#L718C15-L718C15
* The YAML version: https://github.com/aws/sagemaker-python-sdk/blob/052d7e00f236b19260b584ee7d63e2141e5053fb/src/sagemaker/local/image.py#L686

P.S.
Here is where the `deploy` command comes from https://github.com/aws/sagemaker-python-sdk/blob/052d7e00f236b19260b584ee7d63e2141e5053fb/src/sagemaker/local/image.py#L769-L772
